name: my
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #dart:convert: ^2.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/loadjson/historia.json
    - assets/images/